### ISSUE TITLE
BUG - Babies with same name get data mixed

### ISSUE THREAD

**Issue by squickone** [squickone/Feed-Me-Seymore#37]
if two babies have the same name, the data for each baby can get mixed up.

**Comment by shortstack** [comment]
agree we should fix it.... but... hopefully people wouldn't have 2 children with the same name... lol

**Comment by squickone** [comment]
What if George Forman downloads and uses the app. (if you didn't know, all his boys are named george)

**Comment by shortstack** [comment]
wow that's bad...

**Comment by dayelostraco** [comment]
I think all we need to do on this one is remove all instances of "babyName" being used to pass a baby from one intent to another.

**Comment by dayelostraco** [comment]
also, George Forman is crazy...

**Comment by squickone** [comment]
fixed, removed method and replaced with getBaby
